require(shiny)

shinyUI(
  pageWithSidebar(
        headerPanel("Quarter mile time of cars"),
    sidebarPanel(
      sliderInput("a", "Displacement (cu.in)", 230, min = 50,
                   max = 510, step = 20),
      sliderInput("b", "Weight (lb/1000)", 3.2 , min = 1,
                   max = 6, step = 0.2),
      sliderInput("c", "Engine type (V = 0, S = 1)", 0, min = 0, max = 1,
                  step = 1),
      sliderInput('d', 'Number of carburetors', 3, min = 1,
                   max = 8, step = 1)
          ),
    mainPanel(
      h3("Quarter mile time for the features you selected"),
            verbatimTextOutput("qmile"),
      h5("This app allows you to examine how different design features of cars
affect the speed of the car as measured by the quarter mile time."),
      
      h5("This app was generated by fitting a linear regression model
          to data from the 1974 Motor Trends magazine. The model consisted 
          of four variables, the engine displacement, weight of the car,
          engine type (V type or S type) and the number of carburetors. This
          model was generated using backward selection from a model containing
          all design features as regressors to find the model that best explains
          the dataset.These were used to predict the quarter
          mile time for the dataset."),
          
        h5("Move the sliders around to see how the design features listed 
          affect Quarter mile time.")
    )
  )
)
